package com.foobnizz.android.simple.integrations;

public enum SearchBy {
    TOP_50_TRACKS_BY_ARTIST, //
    ALBUMS_BY_ARTIST, //
    SIMILAR_ARTISTS_BY_ARTIST, //
    SIMILAR_50_TRACKS_BY_TRACK, //
    TAGS_BY_TAG, //
    ALL_AUDIO, //

    TRACKS_BY_ALBUM, //
    TRACKS_BY_TAG, //

    TOP_TRACKS_BY_USER, //
    TOP_ARTISTS_BY_USER, //
    LOVED_TRACKS_BY_USER, //
    RECENT_TRACKS_BY_USER, //

    LAST_FM_USER, //
    LAST_FM_ARTIST, //
    LAST_FM_FRIENDS_BY_USER, BACK_BUTTON,

    // VKONTAKTE
    VK_USER_ID, //
    VK_GROUP_ID, //

    VK_USER_ALBUMS, //
    VK_GROUP_ALBUMS, //

    VK_GROUP_AUDIO, //
    VK_USER_AUDIO, //

    VK_USER_ALBUM_AUIO, //
    VK_GROUP_ALBUM_AUDIO,

    VK_USER_FRINDS, //
    VK_USER_GROUPS,
    //
	SEARCH, ROOT, TOP_15_TRACKS_BY_ARTIST, SIMILAR_15_TRACKS_BY_TRACK, LAST_FM_NEIGHBOUR_USERS_BY_USER, LAST_FM_RECOMENDED_ARTISTS_BY_USER

};